version: "3.9"
services:
  db-csu-backend:
    image: mysql:latest
    container_name: my-sql-test
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test1
      MYSQL_USER: user
      MYSQL_PASSWORD: pass1
