# Logging
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate:
        sql: DEBUG
        type.descriptor.sql.BasicBinder: ERROR

spring:
  datasource:
    username: sa
    password: mypass1.
    url: jdbc:sqlserver://localhost:1433;database=TestDb
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.SQLServerDialect
    show-sql: true

  jooq:
    sql-dialect: org.hibernate.dialect.SQLServerDialect


